name: Feature request
description: Suggest an SDK improvement
title: '[feature]: '
labels: ['enhancement']
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or use case
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed API or behavior
    validations:
      required: true
  - type: checkboxes
    id: scope
    attributes:
      label: Scope
      options:
        - label: This is for the xBoard API SDK
          required: true
